"""add sector column into assets table

Revision ID: 49d6a540d836
Revises: 55ae25947fbe
Create Date: 2025-11-28 00:21:51.134250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d6a540d836'
down_revision: Union[str, Sequence[str], None] = '55ae25947fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('sector', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'sector')
    # ### end Alembic commands ###
